[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Bibliotecas corrigidas sem prefixos conflitantes
lib_deps =
    olikraus/U8g2 @ ^2.35.4
    nrf24/RF24 @ ^1.4.5
    ELECHOUSE_CC1101_SRC_DRV

# Esta flag garante que o binário gerado seja compatível com a gravação manual
board_build.partitions = default.csv
