[platformio]
default_envs = esp32dev
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Força o escaneamento profundo de dependências
lib_ldf_mode = deep+
# Garante que as bibliotecas não sejam arquivadas de forma que esconda os headers
lib_archive = no

lib_deps =
    olikraus/U8g2 @ ^2.36.18
    nrf24/RF24 @ ^1.6.1
    ; Nome oficial registrado no PlatformIO
    smartypants/ELECHOUSE_CC1101_SRC_DRV @ ^1.7.9
    
